feat: enhance config for several packages

diff --git a/bin/launch-bar b/bin/launch-bar
--- a/bin/launch-bar
+++ b/bin/launch-bar
@@ -1,44 +1,45 @@
-#!/bin/bash
+#!/bin/sh
 
-MY_HELP="launch-bar
+help() {
+  cat - <<EOF
+launch-bar
 launch a Polybar bar
 
 USAGE
-  launch-bar [--] [-h] <bar>
+  launch-bar -h
+  launch-bar [--] <bar>
 
 FLAGS
       --      treat next arguments as positional arguments
-  -h  --help  print help information and exit
+  -h  --help  print this help message and exit
 
 POSITIONAL ARGUMENTS
-  <bar>  name of the bar to launch"
-
-bar() { [[ $MY_BAR ]] && die "invalid trailing argument: $1"; MY_BAR="$1"; }
-die() { (($#)) && err "$@"; exit 1; }
-err() { echo "launch-bar: ERROR: $@" >&2; }
-
-parse() {
-  while (($#)); do
-    ((MY_RAW)) && { bar "$1"; shift 1; continue; }
-    case $1 in
-      --) MY_RAW=1 ;;
-      -h|--help) echo "$MY_HELP"; exit ;;
-      -*) die "invalid option: $1" >&2 ;;
-      *) bar "$1" ;;
-    esac
-    shift 1
-  done
-  [[ $MY_BAR ]] || die "<bar> not given"
+  <bar>  name of the bar to launch
+EOF
 }
 
-run() {
+err() { echo "launch-bar: ERROR: $*" >&2; }
+die() { [ "$#" -gt 0 ] && err "$@"; exit 1; }
+bar() { [ "$BAR" ] && die "invalid trailing argument: $1"; BAR="$1"; }
+
+parse() {
+  case $1 in
+    -h|--help) help; exit;;
+    --) [ "$2" ] || die "<bar> not given"; bar "$2";;
+    -*) die "invalid argument: $1";;
+    *) bar "$1";;
+  esac
+  [ "$BAR" ] || die "<bar> not given"
+}
+
+main() {
   parse "$@"
-  local file="${XDG_CONFIG_HOME:-$HOME/.config}/polybar/$MY_BAR.ini"
-  [[ -f $file ]] || die "bar file doesn't exist: $file"
-  local tmp=/tmp/polybar-$USER-$MY_BAR
-  [[ -p $tmp ]] && kill $(readlink $tmp | cut -d. -f2)
-  polybar -c "$file" "$MY_BAR" &
+  bar_file="${XDG_CONFIG_HOME:-$HOME/.config}/polybar/$BAR.ini"
+  [ -f "$bar_file" ] || die "bar file does not exist: $bar_file"
+  tmp=/tmp/polybar-$USER-$BAR
+  [ -p "$tmp" ] && kill "$(readlink "$tmp" | cut -d. -f2)"
+  polybar -c "$bar_file" "$BAR" &
   ln -fs /tmp/polybar_mqueue.$! "$tmp"
 }
 
-run "$@"
+main "$@"
diff --git a/sx/sxrc b/sx/sxrc
--- a/sx/sxrc
+++ b/sx/sxrc
@@ -1,52 +1,60 @@
-#!/bin/bash
+#!/bin/sh
 
-HELP='sxrc
+help() {
+  cat - <<EOF
+sxrc
 start X session
 
 USAGE
   sxrc
-  sxrc -c <cmd> ...
-  sxrc [-h] ...
-  sxrc [--] <sesh> ...
+  sxrc -h
+  sxrc -c <cmd>
+  sxrc [--] <sesh>
 
 FLAGS
       --      treat next arguments as positional arguments
-  -h  --help  print help information and exit
+  -h  --help  print this help message and exit
 
 OPTIONS
-  -c  --cmd  <cmd>  set custom command <cmd> to be executed
+  -c  --cmd  <cmd>  set custom command to be executed
 
 POSITIONAL ARGUMENTS
-  <sesh>  set session <sesh> to be started; <sesh> may be "bspwm"'
+  <sesh>  set session to be started; <sesh> may be "bspwm"
+
+If executed with no arguments, it will use "bspwm" as the session to be
+started.
+EOF
+}
+
+err() { echo "sxrc: ERROR: $*" >&2; }
+die() { [ "$#" -gt 0 ] && err "$@"; exit 1; }
 
 bspwm() {
   ~/.fehbg &
-  SXHKD_SHELL=/bin/bash sxhkd ~/.config/sxhkd/bspwm.sxhkdrc &
+  SXHKD_SHELL=/bin/sh sxhkd ~/.config/sxhkd/bspwm.sxhkdrc &
   launch-bar bspwm &
+  dunst &
   exec bspwm
 }
 
-err() { echo "sxrc: ERROR: $@" >&2; }
-die() { (($#)) && err "$@"; exit 1; }
-
 parse() {
   case $1 in
-    '') SESH=bspwm ;;
-    -c|--cmd) [[ $2 ]] || die "<cmd> not given"; CMD="$2" ;;
-    -h|--help) echo "$HELP"; exit ;;
-    --) [[ $2 ]] || die "<sesh> not given"; SESH="$2" ;;
-    -*) die "invalid argument: $1" ;;
-    *) SESH="$1" ;;
+    '') SESH=bspwm;;
+    -c|--cmd) [ "$2" ] || die "<cmd> not given"; CMD="$2";;
+    -h|--help) help; exit;;
+    --) [ "$2" ] || die "<sesh> not given"; SESH="$2";;
+    -*) die "invalid argument: $1";;
+    *) SESH="$1";;
   esac
 }
 
-run() {
+main() {
   parse "$@"
-  [[ $CMD ]] && exec $CMD
+  [ "$CMD" ] && exec $CMD
   case $SESH in
-    bspwm) bspwm ;;
-    *) die "invalid value for <sesh>: $SESH" ;;
+    bspwm) bspwm;;
+    *) die "invalid value for <sesh>: $SESH";;
   esac
 }
 
-run "$@"
+main "$@"
